### ISSUE TITLE
[Question] How easy would it be to have this work with Sublime Text

### ISSUE THREAD

**Issue by Goldenlion5648** [eutropius225/zenscript-mode#2]
This is an awesome idea, having autocomplete for crafttweaker. Would it be possible for this to also be made compatible with sublime text?

**Comment by eutro** [comment]
`zenscript-mode` is written entirely in Emacs Lisp. Sublime Text, to my knowledge, does not support extension in Emacs Lisp, so unfortunately that would not be possible.
